import Config

# Configure your database
if config_env() == :dev do
  # Fetching variables from the system environment, providing defaults if missing
  db_user = System.get_env("DB_USER") || "postgres"
  db_password = System.get_env("DB_PASSWORD") || "my_secure_password_123"
  db_name = System.get_env("DB_NAME") || "fun_library_dev"
  db_host = System.get_env("DB_HOST") || "localhost"
  db_port = String.to_integer(System.get_env("DB_PORT") || "5432")

  config :fun_library, FunLibrary.Repo,
    username: db_user,
    password: db_password,
    hostname: db_host,
    database: db_name,
    port: db_port,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

config :fun_library, :google_books_api_key, System.get_env("GOOGLE_BOOKS_API_KEY")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fun_library, FunLibraryWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cTxoRZp21RBNt3Yq1b6V+Gwoq7hD5MFlRnbnevAoWjEYdyKpPLy01sPf48GIS2Pl",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :fun_library, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
